; This is the list of glk selectors and functions, from Andrew Plotkin's Glk
; Specification, version 0.7.3.
constant glkExit                        $0001
constant glkSetInterruptHandler         $0002
constant glkTick                        $0003
constant glkGestalt                     $0004
constant glkGestaltExt                  $0005
constant glkWindowIterate               $0020
constant glkWindowGetRock               $0021
constant glkWindowGetRoot               $0022
constant glkWindowOpen                  $0023
constant glkWindowClose                 $0024
constant glkWindowGetSize               $0025
constant glkWindowSetArrangement        $0026
constant glkWindowGetArrangement        $0027
constant glkWindowGetType               $0028
constant glkWindowGetParent             $0029
constant glkWindowClear                 $002A
constant glkWindowMoveCursor            $002B
constant glkWindowGetStream             $002C
constant glkWindowSetEchoStream         $002D
constant glkWindowGetEchoStream         $002E
constant glkSetWindow                   $002F
constant glkWindowGetSibling            $0030
constant glkStreamIterate               $0040
constant glkStreamGetRock               $0041
constant glkStreamOpenFile              $0042
constant glkStreamOpenMemory            $0043
constant glkStreamClose                 $0044
constant glkStreamSetPosition           $0045
constant glkStreamGetPosition           $0046
constant glkStreamSetCurrent            $0047
constant glkStreamGetCurrent            $0048
constant glkFilerefCreateTemp           $0060
constant glkFilerefCreateByName         $0061
constant glkFilerefCreateByPrompt       $0062
constant glkFilerefDestroy              $0063
constant glkFilerefIterate              $0064
constant glkFilerefGetRock              $0065
constant glkFilerefDeleteFile           $0066
constant glkFilerefDoesFileExist        $0067
constant glkFilerefCreateFromFileref    $0068
constant glkPutChar                     $0080
constant glkPutCharStream               $0081
constant glkPutString                   $0082
constant glkPutStringStream             $0083
constant glkPutBuffer                   $0084
constant glkPutBufferStream             $0085
constant glkSetStyle                    $0086
constant glkSetStyleStream              $0087
constant glkGetCharStream               $0090
constant glkGetLineStream               $0091
constant glkGetBufferStream             $0092
constant glkCharToLower                 $00A0
constant glkCharToUpper                 $00A1
constant glkStyleHintSet                $00B0
constant glkStyleHintClear              $00B1
constant glkStyleDistinguish            $00B2
constant glkStyleMeasure                $00B3
constant glkSelect                      $00C0
constant glkSelectPoll                  $00C1
constant glkRequestLineEvent            $00D0
constant glkCancelLineEvent             $00D1
constant glkRequestCharEvent            $00D2
constant glkCancelCharEvent             $00D3
constant glkRequestMouseEvent           $00D4
constant glkCancelMouseEvent            $00D5
constant glkRequestTimerEvents          $00D6
constant glkImageGetInfo                $00E0
constant glkImageDraw                   $00E1
constant glkImageDrawScaled             $00E2
constant glkWindowFlowBreak             $00E8
constant glkWindowEraseRect             $00E9
constant glkWindowFillRect              $00EA
constant glkWindowSetBackgroundColor    $00EB
constant glkSchannelIterate             $00F0
constant glkSchannelGetrock             $00F1
constant glkSchannelCreate              $00F2
constant glkSchannelDestroy             $00F3
constant glkSchannelCreateext           $00F4
constant glkSchannelPlaymulti           $00F7
constant glkSchannelPlay                $00F8
constant glkSchannelPlayext             $00F9
constant glkSchannelStop                $00FA
constant glkSchannelSetvolume           $00FB
constant glkSoundLoadHint               $00FC
constant glkSchannelSetVolumeExt        $00FD
constant glkSchannelPause               $00FE
constant glkSchannelUnpause             $00FF
constant glkSetHyperlink                $0100
constant glkSetHyperlinkStream          $0101
constant glkRequestHyperlinkEvent       $0102
constant glkCancelHyperlinkEvent        $0103
constant glkBufferToLowerCaseUni        $0120
constant glkBufferToUpperCaseUni        $0121
constant glkBufferToTitleCaseUni        $0122
constant glkBufferCanonDecomposeUni     $0123
constant glkBufferCanonNormalizeUni     $0124
constant glkPutCharUni                  $0128
constant glkPutStringUni                $0129
constant glkPutBufferUni                $012A
constant glkPutCharStreamUni            $012B
constant glkPutStringStreamUni          $012C
constant glkPutBufferStreamUni          $012D
constant glkGetCharStreamUni            $0130
constant glkGetBufferStreamUni          $0131
constant glkGetLinestreamUni            $0132
constant glkStreamOpenFileUni           $0138
constant glkStreamOpenMemoryUni         $0139
constant glkRequestCharEventUni         $0140
constant glkRequestLineEventUni         $0141
constant glkSetEchoLineEvent            $0150
constant glkSetTerminatorsLineEvent     $0151
constant glkCurrentTime                 $0160
constant glkCurrentSimpleTime           $0161
constant glkTimeToDateUtc               $0168
constant glkTimeToDateLocal             $0169
constant glkSimpleTimeToDateUtc         $016A
constant glkSimpleTimeToDateLocal       $016B
constant glkDateToTimeUtc               $016C
constant glkDateToTimeLocal             $016D
constant glkDateToSimpleTimeUtc         $016E
constant glkDateToSimpleTimeLocal       $016F

constant ioSysGlk                       2

constant gestaltVersion                 0
constant gestaltCharInput               1
constant gestaltLineInput               2
constant gestaltCharOutput              3
constant gestaltCharOutputCannotPrint   0
constant gestaltCharOutputApproxPrint   1
constant gestaltCharOutputExactPrint    2
constant gestaltMouseInput              4
constant gestaltTimer                   5
constant gestaltGraphics                6
constant gestaltDrawImage               7
constant gestaltSound                   8
constant gestaltSoundVolume             9
constant gestaltSoundNotify             10
constant gestaltHyperlinks              11
constant gestaltHyperlinkInput          12
constant gestaltSoundMusic              13
constant gestaltGraphicsTransparency    14
constant gestaltUnicode                 15
constant gestaltUnicodeNorm             16
constant gestaltLineInputEcho           17
constant gestaltLineTerminators         18
constant gestaltLineTerminatorKey       19
constant gestaltDateTime                20
constant gestaltSound2                  21

constant evtypeNone                     0
constant evtypeTimer                    1
constant evtypeCharInput                2
constant evtypeLineInput                3
constant evtypeMouseInput               4
constant evtypeArrange                  5
constant evtypeRedraw                   6
constant evtypeSoundNotify              7
constant evtypeHyperlink                8
constant evtypeVolumeNotify             9

constant keycodeUnknown                 $ffffffff
constant keycodeLeft                    $fffffffe
constant keycodeRight                   $fffffffd
constant keycodeUp                      $fffffffc
constant keycodeDown                    $fffffffb
constant keycodeReturn                  $fffffffa
constant keycodeDelete                  $fffffff9
constant keycodeEscape                  $fffffff8
constant keycodeTab                     $fffffff7
constant keycodePageUp                  $fffffff6
constant keycodePageDown                $fffffff5
constant keycodeHome                    $fffffff4
constant keycodeEnd                     $fffffff3
constant keycodeFunc1                   $ffffffef
constant keycodeFunc2                   $ffffffee
constant keycodeFunc3                   $ffffffed
constant keycodeFunc4                   $ffffffec
constant keycodeFunc5                   $ffffffeb
constant keycodeFunc6                   $ffffffea
constant keycodeFunc7                   $ffffffe9
constant keycodeFunc8                   $ffffffe8
constant keycodeFunc9                   $ffffffe7
constant keycodeFunc10                  $ffffffe6
constant keycodeFunc11                  $ffffffe5
constant keycodeFunc12                  $ffffffe4
constant keycodeMaxValue                28

constant styleNormal                    0
constant styleEmphasized                1
constant stylePreformatted              2
constant styleHeader                    3
constant styleSubheader                 4
constant styleAlert                     5
constant styleNote                      6
constant styleBlockQuote                7
constant styleInput                     8
constant styleUser1                     9
constant styleUser2                     10
constant styleStyleCount                11

constant wintypeAllTypes                0
constant wintypePair                    1
constant wintypeBlank                   2
constant wintypeTextBuffer              3
constant wintypeTextGrid                4
constant wintypeGraphics                5

constant winmethodLeft                  $00
constant winmethodRight                 $01
constant winmethodAbove                 $02
constant winmethodBelow                 $03
constant winmethodDirMask               $0f
constant winmethodFixed                 $10
constant winmethodProportional          $20
constant winmethodDivisionMask          $f0
constant winmethodBorder                $000
constant winmethodNoBorder              $100
constant winmethodBorderMask            $100

constant fileusageData                  $00
constant fileusageSavedGame             $01
constant fileusageTranscript            $02
constant fileusageInputRecord           $03
constant fileusageTypeMask              $0f
constant fileusageTextMode              $100
constant fileusageBinaryMode            $000

constant filemodeWrite                  $01
constant filemodeRead                   $02
constant filemodeReadWrite              $03
constant filemodeWriteAppend            $05

constant seekmodeStart                  0
constant seekmodeCurrent                1
constant seekmodeEnd                    2

constant stylehintIndentation           0
constant stylehintParaIndentation       1
constant stylehintJustification         2
constant stylehintSize                  3
constant stylehintWeight                4
constant stylehintOblique               5
constant stylehintProportional          6
constant stylehintTextColor             7
constant stylehintBackColor             8
constant stylehintReverseColor          9
constant stylehintNUMHINTS              10
constant stylehintjustLeftFlush         0
constant stylehintjustLeftRight         1
constant stylehintjustCentered          2
constant stylehintjustRightFlush        3

constant imagealignInlineUp             $01
constant imagealignInlineDown           $02
constant imagealignInlineCenter         $03
constant imagealignMarginLeft           $04
constant imagealignMarginRight          $05
